# Generated by Django 2.2.2 on 2019-08-14 01:00

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20190805_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='anna_review',
            field=tinymce.models.HTMLField(default="Anna's review"),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.FileField(upload_to='book_img/'),
        ),
    ]
