# Generated by Django 2.2.2 on 2019-09-17 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20190903_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='original_title',
            field=models.CharField(default='Original_title', max_length=200),
        ),
    ]
