# Generated by Django 2.2.2 on 2019-09-21 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20190921_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='name_rus',
            field=models.CharField(default='Name in Russian', max_length=200),
        ),
    ]
