# Generated by Django 2.2.2 on 2019-10-06 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_author_name_rus'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='qoutes',
            field=models.TextField(blank=True, max_length=400),
        ),
    ]
