# Generated by Django 2.2.2 on 2019-10-06 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_book_qoutes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='qoutes',
        ),
    ]
